name: NUCOG CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  gcc-11:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v2
      - name: Testing NUCOG with g++
        uses: ./.github/actions/run_tests
        with:
          compiler: 'g++-11'

  clang-12:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v2
      - name: Testing NUCOG with clang
        uses: ./.github/actions/run_tests
        with:
          compiler: 'clang++'
